links_position:
  default: right
  type: enum
  choices:
    - right
    - left
  description:
    en: "Note that when links are displayed on the left, they're automatically hidden while scrolling within topics to make room for the title"

category_ids:
  type: list
  list_type: simple
  default: "1|2|3"
  description:
    en: "Enter the category id number whose stats you would like displayed."

showPostCount:
  type: bool
  default: true
  description:
    en: "Show the number of posts in each category."
